version: "3"
services:
  frontend:
    build: .
    image: frontend
    build:
       context: .
    container_name: frontend
    networks:
       allnetwork:
          ipv4_address: 172.20.0.2
    ports:
      - "80:80"
    command: ["npm", "run", "buildStart"]
networks:
  default:
    external:
       name: allnetwork
  allnetwork:
    external: true
