version: "3"
services:
  frontend:
    image: ghcr.io/int222-13-49-129/int222:dev
    container_name: frontend
    networks:
       allnetwork:
          ipv4_address: 172.20.0.2
    # ports:
    #   - "80:80"
networks:
  default:
    external:
       name: allnetwork
  allnetwork:
    external: true
